on: [push]

jobs:
  prepare_csv:
    runs-on: ubuntu-latest
    name: Prepare input data
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Convert yaml to csv
      id: yaml2csv
      uses: ./examples/session3/docker-action/
      with:
        yaml: ./examples/session3/contacts.yml
    - name: Archive generated artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist-without-markdown
        path: |
          output/*.txt
    - name: Test generated artifacts in docker stack
      run: |
        docker-compose -f ./examples/session2/servers.yml up -d
        sleep 10
        for file in output/*.txt
        do 
          docker-compose \
            -f examples/session2/servers.yml \
            -f examples/session3/docker-action-compose/loader.yml \
            run data-load ${file}
        done
        docker-compose -f ./examples/session2/servers.yml down
